# Full Stack Configuration
#
# Complete setup with all services enabled and configured with production-ready
# settings. Includes Redis for messaging, PostgreSQL for persistence, and
# Temporal for workflow orchestration.
#
# Use Case:
# - Complete Mycelium deployment
# - Development with all features
# - Full-featured testing environment
# - Reference for production setup
#
# To use this configuration:
#   cp examples/configs/full-stack.yaml ~/.config/mycelium/config.yaml
#   mycelium config validate

version: "1.0"

# Project identifier (customize for your project)
project_name: mycelium-full

# Docker Compose deployment with all services
deployment:
  method: docker-compose
  auto_start: true
  healthcheck_timeout: 90      # More time for all services

# Services configuration
services:
  # Redis: Pub/sub messaging and task queuing
  redis:
    enabled: true
    version: "7"                # Redis 7.x for latest features
    port: 6379                  # Standard port
    persistence: true           # RDB snapshots enabled
    max_memory: "1gb"           # Generous memory for queues
    custom_config:
      maxmemory-policy: "allkeys-lru"  # LRU eviction
      save: "900 1 300 10 60 10000"    # RDB save intervals
      appendonly: "yes"                 # AOF for durability
      appendfsync: "everysec"           # Sync every second

  # PostgreSQL: Persistent data storage
  postgres:
    enabled: true
    version: "15"               # PostgreSQL 15 for performance
    port: 5432                  # Standard port
    database: mycelium          # Database name
    max_connections: 200        # Higher connection pool
    custom_config:
      # Memory configuration (tune based on available RAM)
      shared_buffers: "512MB"         # 25% of RAM
      work_mem: "64MB"                # Per-query memory
      maintenance_work_mem: "256MB"   # Maintenance operations
      effective_cache_size: "2GB"     # OS cache hint

      # WAL configuration
      wal_level: "replica"            # Enable replication
      max_wal_size: "2GB"
      min_wal_size: "160MB"

      # Performance tuning for SSDs
      random_page_cost: "1.1"         # SSD vs 4.0 for HDD
      effective_io_concurrency: "200" # SSD concurrency

  # Temporal: Workflow orchestration
  temporal:
    enabled: true
    ui_port: 8080               # Web UI port
    frontend_port: 7233         # gRPC frontend port
    namespace: default          # Default namespace
