# Temporal Server Deployment and Service for mycelium-demo
# Generated: 2025-10-14 17:39:41

apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
  namespace: mycelium-demo
  labels:
    app: temporal
    component: workflow-engine
    project: mycelium-demo
data:
  DEFAULT_NAMESPACE: default
  DB: postgresql
  DB_PORT: "5432"
  ENABLE_ES: "false"
  DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
  POSTGRES_SEEDS: postgres.mycelium-demo.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: mycelium-demo
  labels:
    app: temporal
    component: workflow-engine
    project: mycelium-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
      project: mycelium-demo
  template:
    metadata:
      labels:
        app: temporal
        component: workflow-engine
        project: mycelium-demo
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          until nc -z postgres.mycelium-demo.svc.cluster.local 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
      containers:
      - name: temporal
        image: temporalio/auto-setup:1.22.0
        ports:
        - containerPort: 7233
          name: frontend
          protocol: TCP
        - containerPort: 8080
          name: ui
          protocol: TCP
        envFrom:
        - configMapRef:
            name: temporal-config
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: TEMPORAL_CLI_ADDRESS
          value: "localhost:7233"
        livenessProbe:
          exec:
            command:
            - tctl
            - --address
            - localhost:7233
            - cluster
            - health
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - tctl
            - --address
            - localhost:7233
            - cluster
            - health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: mycelium-demo
  labels:
    app: temporal
    component: workflow-engine
    project: mycelium-demo
spec:
  selector:
    app: temporal
    project: mycelium-demo
  ports:
  - port: 7233
    targetPort: 7233
    protocol: TCP
    name: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: mycelium-demo
  labels:
    app: temporal
    component: workflow-engine
    project: mycelium-demo
spec:
  selector:
    app: temporal
    project: mycelium-demo
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: ui
  type: LoadBalancer  # Change to NodePort or Ingress as needed
